### ISSUE TITLE
Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by victorporof** [edriang/use-context-selection#2]
I'm getting many of these warnings when dealing with a nested hierarchy of components. Stack traces point to https://github.com/edriang/use-context-selection/blob/master/src/createContext.ts#L16

**Comment by victorporof** [comment]
I think you can work around this by scheduling the "component state" update that triggers the rerender to happen in a microtask.

**Comment by adrian-marcelo-gallardo** [comment]
Hello again! sorry I didn't answered before, I had a busy week at work.

Can you provide me with some example App code in which this is failing, so I can reproduce and dig into the issue? (codesandbox example would be awesome).

I've tried reproducing this with a nested hierarchy of Parent -> children -> children -> children all off them accessing context properties and seems to be working fine for me.

**Comment by adrian-marcelo-gallardo** [comment]
I believe your error might look something like this (if not please share a more elaborated example):
![image](https://user-images.githubusercontent.com/33430733/80851000-8a75c600-8be4-11ea-9817-9be8bc8f0965.png)

In the case of this error message, it happened because I triggered a mutation on my state within the body of a functional component, which is no correct and not-allowed by React.

In this case I did this on purpose, I called an `increment()` function which dispatches a change on the state value stored in Context while rendering a Component. But this is something wrong; if you need to dispatch a change you should do that inside a `useEffect` hook or similar.

**Comment by victorporof** [comment]
Not really. This is because the context dispatcher created by this library can invoke a state setter inside another component, created via the selector functions. There's no other way around this in the most recent version of react, other than using an effect or queueing a micro task, which is why other libraries that attempt to implement this in user land resort to those workarounds.

**Comment by edriang** [comment]
@victorporof, I'll ask you again for a codesandox example, please :pray:!!

On the sample applications I built I couldn't reproduce this error, neither on the state-management library I've built: https://www.npmjs.com/package/react-connect-context-hooks.

I would really appreciate something to reproduce this issue to determine if it is really a bug or if it can be "fixed" by good-practices/recommendations on the README.

**Comment by edriang** [comment]
Hi @victorporof, I'm going to close this issue due inactivity, but feel free to reopen it if you can provide some example to reproduce it.
